### ISSUE TITLE
Missing license in package.json

### ISSUE THREAD

**Issue by szaffarano** [helmetjs/crossdomain#5]
I'm using [pkg](https://github.com/zeit/pkg/) to build my project, and I need that all the package.json files of my dependencies have a licensing attribute.  Please, can you add a license entry in your project?
Thank you

**Comment by EvanHahn** [comment]
Thanks for reporting this. I plan to give this a look on Friday and release a new version.

If you'd like to submit a pull request in the meantime (should be a matter of adding `"license": "MIT"` to `package.json`), I'll take a look at it.

**Comment by szaffarano** [comment]
Done, I submitted a new PR

Thank you

**Comment by EvanHahn** [comment]
Thanks for making the PR! I'll release a new version on Friday.

**Comment by EvanHahn** [comment]
Whoops—leaving this issue open until I deploy a new version.

**Comment by EvanHahn** [comment]
This has been deployed in `helmet-crossdomain@0.2.0`!

**Comment by szaffarano** [comment]
Thanks!
